### ISSUE TITLE
Allow stdin redirection (somehow?)

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pimod#1]
I tried to set a password in the chroot using `RUN bash -c '(echo natur; echo natur) | passwd pi'`, which failed due to the pipe I used. 

There could be a method (some fancy combination of escapes) to have the whole line executed inside the chroot, not only the first part. Please find out and document.

**Comment by gh0st42** [comment]
`RUN bash -c 'echo -e "bushberry\nbushberry" | passwd pi'` works fine

**Comment by gh0st42** [comment]
The errors just don't appear... 
`bash -c` doesn't work at all.

`RUN apt-get -y dist-upgrade` executes.
`RUN /bin/bash -c "apt-get -y dist-upgrade"` doesn't:
```
apt 1.4.8 (armhf)
Usage: apt-get [options] command
       apt-get [options] install|remove pkg1 [pkg2 ...]
       apt-get [options] source pkg1 [pkg2 ...]

apt-get is a command line interface for retrieval of packages
and information about them from authenticated sources and
for installation, upgrade and removal of packages together
with their dependencies.
[..]
```

**Comment by geistesk** [comment]
I will take a look at this soon.

A hacky workaround would be creating an install script, `INSTALL`ing it, `RUN` it and `RUN rm` it afterwards.
