### ISSUE TITLE
Link / bind mount QEMU

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pimod#17]
The QEMU static binaries are currently copied to the guest image. This is not necessary as the binaries themselves are not needed in the image afterwards.

Instead, I suggest to either bind mount individual binaries or expand the PATH and bind mount a folder.

**Comment by geistesk** [comment]
This issue is linked to #16. Perhaps, we should add a `PATH` overlay at first, which can be altered both by a Pifile and some setup / teardown routines.
