### ISSUE TITLE
OpenWRT test fails after implementing PATH feature

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pimod#22]
see https://github.com/Nature40/pimod-ci/commit/d220adcaff7dcb129f6315da991ee3e1c6949b69/checks?check_suite_id=311137370

**Comment by geistesk** [comment]
I just tested the following Pifile successfully, which looks identically to the failed job.

```
FROM https://downloads.openwrt.org/releases/18.06.4/targets/brcm2708/bcm2710/openwrt-18.06.4-brcm2708-bcm2710-rpi-3-ext4-factory.img.gz

RUN cat /etc/os-release
```

Furthermore, the error looks like a failed `mount -a` to me. The guest fails to execute both the internal `mount` and the `cat` command. I'm not quite sure what is broken there. However, I cannot reproduce this behavior.

**Comment by jonashoechst** [comment]
I started to investigate using the interactive debug option, however I do not quite understand, why the chroot environment does not work in this case.

**Comment by jonashoechst** [comment]
Something is deliberately broken here, not even Raspbian does work ATM. It fails for me, fails in CI.
Please have a look at this @geistesk.

**Comment by jonashoechst** [comment]
The bug was introduced by moving the QEMU binaries to a temporary folder which is added to the PATH. However, the path of the binaries is resolved when enabling the architecture using update-binfmts.

The enabled path is available on the host system but not on the guest.
