### ISSUE TITLE
Permissive license

### ISSUE THREAD

**Issue by aniongithub** [Nature40/pimod#32]
This project seems like a great idea, with tons of potential for not just humanitarian purposes but a lot more to enable people to use commodity hardware. See my [pi-bootstrap](https://github.com/aniongithub/pi-bootstrap/) repo for something similar, but based on pi-gen. I allow injection of secrets for ready-to-connect images as well as complete modification/re-arranging the steps for even a base image via an externally sourced config, among other things.

However, the GPL v3 license on this repo. makes it impossible to use in a commercial setting or derive freely without going GPL myself. Would you consider licensing it under something more permissive, say the MIT license? I believe this would be of benefit to the maker community at large.

**Comment by oxzi** [comment]
> However, the GPL v3 license on this repo. makes it impossible to use in a commercial setting or derive freely without going GPL myself.

IANAL, but this should only be relevant for libraries. However, pimod is a tool which you can use under its free license. The GNU GPL does not affect the Pifiles or even the images you create.

**Comment by aniongithub** [comment]
That's true if I only intended to use it as it is. However, I would like to extend this mechanism to work with other SBCs and extend the commands and toolset. Even forking it would mean requring continuation of the GPL V3 license - this is the reason I asked about a more permissive license.
