### ISSUE TITLE
Current version on GitHub Marketplace

### ISSUE THREAD

**Issue by oxzi** [Nature40/pimod#36]
It seems like some permissions for GitHub's Marketplace have changed in the meantime.
This results in us - or at least me, as only an organization member - to be unable to publish the latest pimod version as a GitHub Action.

The following screenshot is the view I am getting if I want to draft a new release:
![2021-10-04-170905_750x106_scrot](https://user-images.githubusercontent.com/8402811/135876480-d048e2ca-9e64-4cb8-8573-1e81320c8386.png)

Could you please take a look, @jonashoechst? Thanks a lot.

**Comment by jonashoechst** [comment]
I've accepted the respective Agreement and published the recent version to GitHub Marketplace. As it is accepted now on behalf of the organization, you should be able to do this as well for upcoming releases - at least if GitHub won't update their agreement again...
