### ISSUE TITLE
Chaining commands with && has unexpected behaviour

### ISSUE THREAD

**Issue by zabealbe** [Nature40/pimod#47]
`RUN apt update && apt install git` runs `apt install` in host environment

`RUN apt update`
`RUN apt install git`
fixes the issue, however this can lead to [hours wasted in debugging time](http://source:trust.me) expecially if you expect it to work similarly to a Dockerfile.
I think a fix is needed if possible, however I did not investigate if the fact that .pimod is just a bash file is a barrier for an actual fix.

**Comment by oxzi** [comment]
Thanks for trying out pimod and reporting back.

I am sorry hearing your bug hunting odyssey regarding the bashism. Without any intention to sound rude, this is exactly the [described behavior](https://github.com/Nature40/pimod#run-cmd-params). However, especially with the Docker-inspired design, this is might be counterintuitive.

As long as we don't change the software's main architecture - the Pifile is just Bash and the commands are loaded for each step -, I don't see how we can prevent this. And, btw, I don't want to change this design.
What I could think of would be a new _pre-stage_ checking the Pifile for lines containing unescaped `RUN` commands with other Bash commands and printing a warning. How does this sound to you?
