### ISSUE TITLE
Feature request: provide some kind of access to host files

### ISSUE THREAD

**Issue by sensslen** [Nature40/pimod#49]
For our appliance we do create custom apt packages that we then install on the raspberrry pi image. Currently we have to copy the files to the root fs (by using the install command), execute apt to install the files and then remove them again. It would be really nice if there was a possibility to bind mount a folder to the chroot environment which then would allow to use the files in the bind mounted folder.

**Comment by oxzi** [comment]
Closed by #50.

Thanks a lot for bringing forward your feature request and implementing it.
