### ISSUE TITLE
Infer image name from Pifile name

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pimod#6]
When not configured explicitly (via TO ...) the name of the resulting image can also be referred from the Pifile, e.g. BaumBox.Pifile would result in the image being called BaumBox.img.

**Comment by gh0st42** [comment]
If removing TO is desired then removing FROM might also be a good idea. If no FROM is given just expect a default image (e.g. `/raspbian.img`). This can be easily overmapped by a volume. Therefore, just provide the input image as parameter to the wrapper script and omit changing the FROM line every time you switch between different input images.

**Comment by jonashoechst** [comment]
To clarify: I was not talking about removing TO, but extending the current functionality. Currently, if TO is not specified, the resulting image is written to rpi.img.

**Comment by gh0st42** [comment]
Similarly FROM could be optional, no need to remove it completely since it is already implemented.
Would make preparing several images with same setup easier (e.g. raspbian-lite and then an raspbian-full)
