### ISSUE TITLE
Create docker images for linux/arm/v7

### ISSUE THREAD

**Issue by patrickelectric** [Nature40/pimod#65]
I'm trying to run pimod in a raspberry since some binds need to access the raspberry hardware to create the image, but that's not possible since there is no docker for the raspberry architecture.

**Comment by oxzi** [comment]
Thanks for reporting this issue!

The latest Docker images are now also being built for linux/arm/v7, as shown on Docker Hub <https://hub.docker.com/r/nature40/pimod/tags>. Please try them out and report back if everything works or something needs to be adjusted.

**Comment by patrickelectric** [comment]
Awesome @oxzi! I'll check it out!

**Comment by oxzi** [comment]
@patrickelectric: Did you find the time for checking it out?
